/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
add_1_svc(arguments *argp, struct svc_req *rqstp)
{
	static int  result;

		result = argp->param1 + argp->param2;

	return &result;
}

int *
sub_1_svc(arguments *argp, struct svc_req *rqstp)
{
	static int  result;

		result = argp->param1 - argp->param2;

	return &result;
}

int * mul_1_svc(arguments *argp, struct svc_req *rqstp){

	static int  result;

		result = argp->param1 * argp->param2;

	return &result;
}

int * div_1_svc(arguments *argp, struct svc_req *rqstp){

	static int  result;

		result = argp->param1 / argp->param2;

	return &result;
}


